### ISSUE TITLE
提供 SOFAArk 多 ClassLoader 兼容性测试的框架，方便用户进行低成本的验证。

### ISSUE THREAD

**Issue by CodeNoobKing** [koupleless/koupleless#108]
### Feature description
目前用户验证多 SOFAArk 下 ClassLoader 的兼容性验证需要拆分模块，成本很高，而且排查复现起来涉及整个工程的构建，用户也很难提供 MVP。
为了简化兼容性治理的流程，以及降低用户的接入成本，因此我们需要一种测试框架，可以低成本地，在用户不拆分工程的前提下验证部分中间件 / 公共逻辑在 SOFAArk 多 ClassLoader 模式下的兼容性。

**Comment by lvjing2** [comment]
fixed by https://github.com/koupleless/runtime/pull/24 https://github.com/koupleless/runtime/pull/26
