### ISSUE TITLE
【运行时缺陷】当 NACOS 配置中开启了 nacos.discovery.auto-register=true 的时候，再次安装时会报错 “Client not connected, current status:SHUTDOWN” 

### ISSUE THREAD

**Issue by CodeNoobKing** [koupleless/koupleless#126]
### Feature description

当 NACOS 配置中开启了 nacos.discovery.auto-register=true 的时候，再次安装时会报错 “Client not connected, current status:SHUTDOWN” 

### Additional notes

Add other notes if necessary.

**Comment by gaosaroma** [comment]
用户使用问题
