### ISSUE TITLE
模块依赖jar版本如果是aa-1.0以字符开头其无法正确被基座委托加载

### ISSUE THREAD

**Issue by xiaofc999** [koupleless/koupleless#164]
### Describe the question or bug

如果有个jar的版本是类似 aa-1.0这种字符开头的话，declared-libraries用mvn dependency:tree生成出来是正常的artifactId, 但是到了BizModel里String artifactId = JarUtils.parseArtifactId(jarFilePath)取到的是artifactId-aa这样的，导致如果模块被排掉的包如果委托基座加载会找不到。

<img width="626" alt="企业微信截图_17109021986168" src="https://github.com/koupleless/koupleless/assets/23025624/3a2c9a42-b36b-481a-b413-67c60b48c217">

<img width="508" alt="企业微信截图_17109022486675" src="https://github.com/koupleless/koupleless/assets/23025624/05a33ebe-807b-4e05-91eb-d2852516e417">

如果解析各种奇怪版本的artifactId 比较麻烦的话，是否可以考虑增加一个在ark打包插件里手动append自定义declared-libraries的能力呢？

### Environment

- Koupleless version (see CURRENT_VERSION.txt):
- SOFAArk version:2.2.7
- JVM version (e.g. `java -version`):jdk8
- OS version (e.g. `uname -a`):
- Kubernetes version:1.0.0

**Comment by lvjing2** [comment]
fixed at koupleless runtime 1.0.2-SNAPSHOT
