### ISSUE TITLE
koupleless.io 文档优化

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#166]
1. 点击导航会自动跳到页首，导致看不到点击后导航的标题
![image](https://github.com/koupleless/koupleless/assets/3754074/12454728-78e8-4b6e-bad2-b5647b7f2109)

2. 目录层级较多，可以考虑增加折叠按钮
![image](https://github.com/koupleless/koupleless/assets/3754074/16b7a769-9678-4583-8b2d-4e7e78a5001e)
3. 首页的英文班，当前一些文字还有图片里的文字还是中文的，展示起来比较奇怪
![image](https://github.com/koupleless/koupleless/assets/3754074/ee670e93-de43-49c4-8560-b1fec92d9789)

**Comment by lylingzhen** [comment]
第二个看一下用户需求，如果用户有需求我再搞一下，先标记完成。
