### ISSUE TITLE
模块apollo开启提前加载后基座静态合并启动时模块apollo初始化报错

### ISSUE THREAD

**Issue by xiaofc999** [koupleless/koupleless#167]
### Describe the question or bug

如果模块的apollo打开了提前加载apollo.bootstrap.eagerLoad.enabled=true，然后基座和模块一起静态启动的话，模块启动阶段apollo初始化会报错

### Steps to reproduce

基座和模块都依赖apollo, 其模块中的apollo没有设置为provided, 模块中的apollo.bootstrap.eagerLoad.enabled=true
选择静态合并启动-Dcom.alipay.sofa.ark.static.biz.dir=./biz
<img width="842" alt="企业微信截图_17110277636245" src="https://github.com/koupleless/koupleless/assets/23025624/a9581d96-8456-4a99-8c6b-7280533ec9ab">

![image](https://github.com/koupleless/koupleless/assets/23025624/9a76f2a0-d315-4539-8723-0bf89b7d0d79)

![image](https://github.com/koupleless/koupleless/assets/23025624/d43c1d21-da99-4c69-91a7-e62e568cd9db)

### Environment
- apollo 16.0
- springboot 2.3.12
- Koupleless version (see CURRENT_VERSION.txt): 1.0.0
- SOFAArk version: 2.2.7
- JVM version (e.g. `java -version`):jdk8
- OS version (e.g. `uname -a`):
- Kubernetes version:

**Comment by xiaofc999** [comment]
apollo打开了提前加载apollo.bootstrap.eagerLoad.enabled的话
模块启动时ConfigFileApplicationListener里加载apollo的EnvironmentPostProcessor的问题
<img width="602" alt="企业微信截图_17116068001748" src="https://github.com/koupleless/koupleless/assets/23025624/11cd9f8e-bf2f-4a93-b483-6665558f77d5">

这个问题貌似springboot2.5.x版本做了优化的口子
https://github.com/spring-projects/spring-boot/issues/26126
否则只能自己去使用加个ark-plugin去覆盖ConfigFileApplicationListener改下这边加载EnvironmentPostProcessor的逻辑把当前的BizClassloader作为参数。
不知道是否还有其他更好的解决方案。

**Comment by gaosaroma** [comment]
目前较为合适的方案是写一个 ark-plugin 去适配 springboot 2.3.x ，见 https://github.com/koupleless/koupleless/issues/188
该问题已经修复，见 https://github.com/koupleless/runtime/pull/31
