### ISSUE TITLE
业务模块ark-biz包无法打包scope为system的依赖项的问题

### ISSUE THREAD

**Issue by huyuans** [koupleless/koupleless#169]
业务模块的pom文件声明了<scope>system<scope>的依赖项并指定了<systemPath>，构建完成后ark-biz包中没有对应的目录jar包，导致执行业务时找不到相关jar包的类，报错。

**Comment by lvjing2** [comment]
考虑增加类似 的逻辑springboot 打包插件里的 <includeSystemScope>true</includeSystemScope>，配上这个依赖认为是要打包进入的jar，如果要瘦身可以通过配置文件进行瘦身。
