### ISSUE TITLE
【模块自动瘦身方案二】支持导出基座依赖的pom方便模块瘦身

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#20]
模块瘦身时，经常需要判断基座有哪些依赖，需要有一个机制方便的看到基座的依赖列表，方便瘦身
比如这样：
![image](https://github.com/sofastack/sofa-serverless/assets/2871725/2046d64b-8c2b-4a71-9363-c464635c7c4a)

**Comment by lvjing2** [comment]
两个方案各有优劣：
### 方案一：基于 rules.txt 的排包方案
#### 优势
1. 模块使用比较简单，只需导入即可
#### 劣势
1. 如果基座没有依赖，而模块里又被自动排包掉，需要基座再额外引入进来。
2. 模块可能排包过多，例如 org.springframework.* 的部分希望 compile 依赖，则没有很好支持方式。
3. 模块可能无法做到较为彻底的瘦身
4. 列表需要平台长期维护

### 方案二：基于基座 pom依赖列表的排包方案
#### 优势
与基座的依赖关联比较紧密，不会出现模块拍完包之后，运行时找不到依赖的问题

#### 缺陷
1. 基座的依赖会改变，基座与模块关联太强，可能因为变化之后的不在预期范围内的情况方式。
2. 模块手动排包成本太高，模块自动排包则需要提供允许自动以不排包的方式

**Comment by lvjing2** [comment]
考虑方案一的设计初衷，就是放入必须下沉基座的依赖，同时也兼顾简化使用。所以对于方案一的两个问题，可以考虑如果基座缺失依赖，则让基座添加依赖；如果排包过多，只要不影响启动的就默认排包掉，如果是影响启动的，则需要修改配置从而支持默认不拍影响启动的包。

考虑方案二，一定需要具备自动化排包能力，如果使用自动化排包能力，目前看不方便给用户自定义配置不排包依赖。另外模块需要pom里引入基座 bom，导致模块改造成本存在与基座代码耦合的行为，导致改造成本变高。另外由于基座依赖的变动，以及存在基座多个分支里如果依赖不同的情况，可能出现不在预期的问题。

考虑继续采用方案一，遇到方案一的两个问题，第一个问题由用户增加基座依赖解决，第二个问题继续强制排包掉（除非排包会导致启动失败，则修改 rules.txt 配置文件），第三个问题需要用户容忍这部分模块jar大小的成本，第四个问题平台会长期维护这份配置的更新。
cc @yuanyuancin

**Comment by lvjing2** [comment]
结论，两种作为不同场景提供能力，供选择使用：
1、rule.txt：不需要知道基座依赖，也对基座依赖的版本不敏感，想快速迁移瘦身的模式
2、pom：尽量复用基座依赖，彻底瘦身，想知道基座哪些已经有了，新建的模块

**Comment by qq290584697** [comment]
我觉得这两个方案是可以结合起来使用的。
通过rule.txt进行排包，但是通过pom自动生成可以影响启动的排包。

**Comment by lvjing2** [comment]
@qq290584697 你是说一个项目里同时使用者两种吗？

**Comment by qq290584697** [comment]
@lvjing2 我的意思是，从结果上看，只使用rule.txt
但是提供工具会自动添加或者减少会导致启动失败的内容

**Comment by lvjing2** [comment]
在 https://github.com/koupleless/koupleless/issues/242 会提供该能力，放在 https://github.com/koupleless/koupleless/issues/242 跟进
