### ISSUE TITLE
模块使用 tomcat 时，启动与运行时的 classLoader 不一致

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#212]
### Feature description

不管是否使用 tomcat，模块启动开始时，sofaark 都会通过强制设置当前线程为 BizClassLoader，然后再进行模块的启动，所以此时模块启动时通过 Thread.currentThread().getContextClassLoader() 获得的都是 BizClassLoader

![image](https://github.com/koupleless/koupleless/assets/3754074/e590d303-85c4-4c0d-842c-c1f44ad09c0e)

然后模块 tomcat 在启动时，会通过 `org.apache.catalina.loader.WebappLoader#createClassLoader` 调用 `com.alipay.sofa.ark.web.embed.tomcat.ArkTomcatEmbeddedWebappClassLoader#ArkTomcatEmbeddedWebappClassLoader(java.lang.ClassLoader)`，将模块对应请求 handler 绑定在 ArkTomcatEmbeddedWebappClassLoader 上（父类为 bizClassLoader）

这就导致了，启动时初始化的一些资源或者缓存的 classLoader，与实际web 请求处理时线程上下文的  classLoader 不一致。如果初始化时，通过 classLoader 缓存的一些信息，web请求在执行时就无法通过线程上下文的 classLoader 获取到。

### 解决方案

尝试在模块启动的时候，在初始化 `ArkTomcatEmbeddedWebappClassLoader` 之后将启动的线程上下文 classLoader 更换为新创建的 `ArkTomcatEmbeddedWebappClassLoader`

**Comment by lvjing2** [comment]
增加 web filter，进行 classLoader 切换，实测有效。
![image](https://github.com/koupleless/koupleless/assets/3754074/8be8494d-3f79-4e82-ba78-59313fa95c2a)

**Comment by 1034323716** [comment]
这个拦截器后续是否会提交到adapter模块上？

**Comment by 1034323716** [comment]
我之前还以为这样是符合预期的，其实现在用BizClassLoader的地方还挺多的，是否可以提供一台工具获取到当前模块的ClassLoader

**Comment by lvjing2** [comment]
> 这个拦截器后续是否会提交到adapter模块上？

会的，1.2.0 会带上

**Comment by lvjing2** [comment]
> 我之前还以为这样是符合预期的，其实现在用BizClassLoader的地方还挺多的，是否可以提供一个工具获取到当前模块的BizClassLoader或者BizModel @lvjing2

一般是通过获取模块里的类，来反向获取模块 bizClassLoader 的
