### ISSUE TITLE
不同模块操作不同的业务库

### ISSUE THREAD

**Issue by xwh1108** [koupleless/koupleless#222]
在微服务日常场景下,通常是一个微服务对应一个数据库,koupleless虽然可以模块定义自身的数据源,但是在文档中提到尽可能复用基座数据源,那在这种多数据源的场景下,如何将多数据源沉淀到基座?

**Comment by lvjing2** [comment]
模块自身其实也可以自定义数据源的，建议服用基座只是为了降低模块的资源消耗、提升启动速度。所以不同模块操作不同数据源1. 一种方式是可以不下沉基座
这种与普通 springboot 开发无区别
2. 另一种方式是下沉基座
这种需要基座先定义了多个数据源，不同模块里引用不同的数据源，这个没太明白和当前官网介绍的单数据源的复用方式不同在哪？

**Comment by xwh1108** [comment]
主要是下沉基座,基座采用常用的多数据源框架是否会导致其他问题比较疑问

**Comment by xwh1108** [comment]
> 模块自身其实也可以自定义数据源的，建议服用基座只是为了降低模块的资源消耗、提升启动速度。所以不同模块操作不同数据源1. 一种方式是可以不下沉基座 这种与普通 springboot 开发无区别 2. 另一种方式是下沉基座 这种需要基座先定义了多个数据源，不同模块里引用不同的数据源，这个没太明白和当前官网介绍的单数据源的复用方式不同在哪？

主要是下沉基座,在基座中采用多数据源框架,是否和部分能力会冲突比较好奇

**Comment by lvjing2** [comment]
方便加群沟通吗？
