### ISSUE TITLE
模块多配置的方式不支持 key value 的方式传入 spring profile 配置

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#227]
### 问题描述
模块多配置的文档介绍在这里，https://koupleless.io/docs/tutorials/module-development/module-multi-application-properties/ ，使用时发现两个问题：
1. 如果使用 -Dspring.profiles.active=dev 的方式，不仅会读取到：

- config/${bizName}/application-${profile}.properties
- config/${bizName}/application.properties

还会读取到：

- resources/application-${profile}.properties
- resources/application.properties

![image](https://github.com/koupleless/koupleless/assets/3754074/ad6eb375-8918-471c-a554-eb39c875c2f5)

2. 当通过 --spring.profiles.active=dev 的方式执行时，基座能够读取到正确 profile 的 application.properties，但是模块里读取不到对应的 profile 值，从而报如下错误

![image](https://github.com/koupleless/koupleless/assets/3754074/7b286f9f-bc50-447f-8650-bf509042f00c)

### 问题原因
模块在处理多配置的逻辑，读取 profile 的方式只支持如图里的两种
![image](https://github.com/koupleless/koupleless/assets/3754074/2e3446e1-9382-43ee-8a6b-abaf270e9b1e)

### 问题修复
需要支持 --key=value 的方式传入 profile

**Comment by gaosaroma** [comment]
模块不支持启动参数配置，请把启动参数中的 --spring.profiles.active=dev 配置为 application.properties 中的 spring.profiles.active=dev
