### ISSUE TITLE
多模块的配置文件应该避免相互污染

### ISSUE THREAD

**Issue by foodoon** [koupleless/koupleless#228]
![image](https://github.com/koupleless/koupleless/assets/8012861/29ec48bf-43e5-4696-881e-fb5e599bd6d0)
同时存在以下配置文件，测试发现以模块方式运行的时候同时也会加载2和3，导致相互污染。希望在模块运行的时候只加载配置1.在非kuoupleless环境运行的时候只加载2和3
 1.resources/config/biz/application-daily.yml
 2.resources/application-daily.yml
 3.resources/application.yml

**Comment by gaosaroma** [comment]
模块启动时默认会读取模块自身的资源文件：resources/application-${profile}.yml 和 resources/application.yml
模块需要做多部署单元（模块一份代码用不同的配置部署到不同基座）时，才会使用到 config/${bizName}/application-${profile}.yml 和 config/${bizName}/application.yml，同时也会读取 resources/application-${profile}.yml 和 resources/application.yml。其中，config/${bizName}/application-${profile}.yml 和 config/${bizName}/application.yml 的优先级比 resources/application-${profile}.yml 和 resources/application.yml 高。

**Comment by foodoon** [comment]
通过增加YML配置的方式可以解决问题，譬如增加一个application-module-daily.yml。在启动里执行Profiles=module-daily
