### ISSUE TITLE
新版模块瘦身方案

### ISSUE THREAD

**Issue by gaosaroma** [koupleless/koupleless#242]
背景：
模块二方包不下沉、模块和基座依赖版本不一致、容易导致 class not found 问题，用户侧不友好；模块不瘦身会让模块本身比较大
解决思路：
● 用户侧使用：
  - [x] 打出 基座 facade 包，模块统一以 provided 方式引入
● 平台侧防护：
  ○ 用户开发时，提示不一致包：IDE 插件提示？
  ○ 用户打包时，提示需要瘦身的包？

**Comment by lvjing2** [comment]
包含该 issues： https://github.com/sofastack/sofa-ark/issues/957

**Comment by lvjing2** [comment]
平台侧能力放在 https://github.com/koupleless/koupleless/issues/318  完成
