### ISSUE TITLE
【Springboot AOP needs adapter】java.lang.IllegalArgumentException: interface **Repository is not visible from class loader.

### ISSUE THREAD

**Issue by limingxing5026** [koupleless/koupleless#244]
Error happened when install a biz jar with JPA repositories.
Here is the error message: 
Caused by: java.lang.IllegalArgumentException: interface **Repository is not visible from class loader.

When I debug this method JdkDynamicAopProxy.getProxy in Spring AOP and I found the class loader AOP should use to create new proxy seem incorrect.

Code snippet:
public Object getProxy(@Nullable ClassLoader classLoader) {
	if (classLoader == null || classLoader.getParent() == null) {
		classLoader = getClass().getClassLoader();
	}
	return Proxy.newProxyInstance(classLoader, this.proxiedInterfaces, this);
}

Due to the parent of biz class loader should always be null, the biz class loader which supported to be used would never be used.

### Environment

- Koupleless version:1.2.0
- SOFAArk version: 2.2.10
- JVM version (e.g. `java -version`): JDK 8
- Spring Boot: 2.7.12
- Spring-AOP:5.3.27

**Comment by lvjing2** [comment]
FAQ 中有类似记录：
https://koupleless.io/docs/faq/faq/#%E6%A8%A1%E5%9D%97%E5%90%AF%E5%8A%A8%E5%9C%A8-jdkdynamicaopproxygetproxy-%E6%8A%A5%E9%94%99-xxx-referenced-from-a-method-is-not-visible-from-class-loader

**Comment by lvjing2** [comment]
![image](https://github.com/koupleless/koupleless/assets/3754074/cbec1d42-0895-46ee-a924-b166f24301ed)

**Comment by limingxing5026** [comment]
Add the adapter and it works now : )

**Comment by lvjing2** [comment]
需要为 spring aop 提供相应的 adapter

**Comment by lvjing2** [comment]
fixed by https://github.com/koupleless/adapter/pull/26
