### ISSUE TITLE
添加启动参数spring.config.additional-location=xxx,安装biz时出现空指针异常

### ISSUE THREAD

**Issue by zhuchaowei24** [koupleless/koupleless#247]
![image](https://github.com/koupleless/koupleless/assets/29916440/954e24b1-864f-4b36-a4db-780fa3e3cf67)
字符串需要空指针判断，目前是通过同时添加启动参数-Dspring.config.location=xxx -Dspring.config.additional-location=xxx绕过该报错。
 另外，想了解一下注释中有提到：(  // 禁用模块 spring.config.location 和 spring.config.additional-location) ，这个是不支持biz模块指定配置文件路径吗

**Comment by lvjing2** [comment]
你好，这个问题已经修复，可以升级下这两个版本
sofa.ark.version -> 2.2.11
koupleless.runtime.version -> 1.2.1-SNAPSHOT

**Comment by lvjing2** [comment]
已修复
