### ISSUE TITLE
Confuse error message, when execute maven install,     need prerequisition check, and clear error message

### ISSUE THREAD

**Issue by neil4dong** [koupleless/koupleless#254]
### Describe the question or bug

`koupleless-base-build-plugin`   has perquisition,  but not clear show in the execution error message.
underlying, the plugin execute mvn dependency:tree  though the command to obtain the dependencies for the plugin. 
but the user not necessary should have the mvn command in path.  

`koupleless-base-build-plugin`  有先决依赖， 依赖path中有mvn命令， 当没有mvn命令时， 报错很迷惑，只是没有正确的提示引导用户去配置mvn. 

### Expected behavior

obtain dependencies though the the Maven Plugin API instead of mvn dependency:tree.
or make a clear error message to tell the user to set the java and mvn in path.

通过maven plugin内部的API去调用dependency:tree.
或者清晰的提示用户，需要在path中有java和mvn命令。  

### Actual behavior

package failed, and cannot get any usage information from the error message.  

打包失败，看不出是因为缺少mvn命令

### Steps to reproduce

Steps to reproduce the problem:

### Environment

- Koupleless version (see CURRENT_VERSION.txt): 2.1.1
- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Kubernetes version:

**Comment by lvjing2** [comment]
add tips in this [commit](https://github.com/koupleless/docs/pull/42/commits/d1dc6425d79a54e95766bd66cb2a66aa667c439e)

**Comment by lvjing2** [comment]
这是由于 sofaArk 模块打包时候需要执行 maven dependecy:tree 解析依赖树，导致的。不属于 koupleless-base-build-plugin 的问题，目前通过文档里注明前置条件来解决。故暂时不需要 pr 来解决该问题。
