### ISSUE TITLE
StaticBatchInstallEventListener防止重复部署逻辑失效

### ISSUE THREAD

**Issue by loong-coder** [koupleless/koupleless#260]
### Describe the question or bug
在引入了SpringCloud的情况下，合并部署时，在启动基座过程中会重复实例化StaticBatchInstallEventListener对象，导致现有防止重复部署逻辑失效
![image](https://github.com/koupleless/koupleless/assets/101961800/12f75de2-98a4-4834-9068-06c4c033096c)

A clear and concise description of what the question or bug is.

### Actual behavior

A clear and concise description of what actually happened.

### Steps to reproduce

Steps to reproduce the problem:

### Environment

- Koupleless version (see CURRENT_VERSION.txt):
- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Kubernetes version:

**Comment by lvjing2** [comment]
fixed by https://github.com/koupleless/runtime/pull/117
