### ISSUE TITLE
模块卸载报错

### ISSUE THREAD

**Issue by loong-coder** [koupleless/koupleless#262]
### Describe the question or bug

A clear and concise description of what the question or bug is.

卸载失败，返回信息”
{"code":"CMD_PROCESS_INTERNAL_ERROR","errorStackTrace":"com.alipay.sofa.koupleless.arklet.core.common.exception.ArkletRuntimeException: com.alipay.sofa.ark.exception.ArkRuntimeException: mark and delete biz temp work dir error: D:\\code\\coexist\\temp\\biz-schedule-1.0-SNAPSHOT-20240622180136943-unpack -> D:\\code\\coexist\\temp\\biz-schedule-1.0-SNAPSHOT-20240622180136943-unpack-1719050532184-deleted\r\n\tat com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.UninstallBizHandler.handle(UninstallBizHandler.java:54)\r\n\tat com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.UninstallBizHandler.handle(UninstallBizHandler.java:39)\r\n\tat com.alipay.sofa.koupleless.arklet.core.command.CommandServiceImpl.process(CommandServiceImpl.java:176)\r\n\tat com.alipay.sofa.koupleless.arklet.core.api.tunnel.http.netty.NettyHttpServer$NettyHttpHandler.channelRead0(NettyHttpServer.java:164)\r\n\tat com.alipay.sofa.koupleless.arklet.core.api.tunnel.http.netty.NettyHttpServer$NettyHttpHandler.channelRead0(NettyHttpServer.java:145)\r\n\tat io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\r\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)\r\n\tat io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\r\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\r\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)\r\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\r\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)\r\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\r\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\r\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\r\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)\r\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\r\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\r\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\r\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\r\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\r\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:840)\r\nCaused by: com.alipay.sofa.ark.exception.ArkRuntimeException: mark and delete biz temp work dir error: D:\\code\\coexist\\temp\\biz-schedule-1.0-SNAPSHOT-20240622180136943-unpack -> D:\\code\\coexist\\temp\\biz-schedule-1.0-SNAPSHOT-20240622180136943-unpack-1719050532184-deleted\r\n\tat com.alipay.sofa.ark.container.model.BizModel.recycleBizTempWorkDir(BizModel.java:556)\r\n\tat com.alipay.sofa.ark.container.model.BizModel.stop(BizModel.java:377)\r\n\tat com.alipay.sofa.ark.api.ArkClient.uninstallBiz(ArkClient.java:247)\r\n\tat com.alipay.sofa.koupleless.arklet.core.ops.UnifiedOperationServiceImpl.uninstall(UnifiedOperationServiceImpl.java:102)\r\n\tat com.alipay.sofa.koupleless.arklet.core.command.builtin.handler.UninstallBizHandler.handle(UninstallBizHandler.java:46)\r\n\t... 35 more\r\n","message":"Internal Error: com.alipay.sofa.ark.exception.ArkRuntimeException: mark and delete biz temp work dir error: D:\\code\\coexist\\temp\\biz-schedule-1.0-SNAPSHOT-20240622180136943-unpack -> D:\\code\\coexist\\temp\\biz-schedule-1.0-SNAPSHOT-20240622180136943-unpack-1719050532184-deleted"}
![Uploading image.png…]()

卸载过程中，biz-base-feign-1.0-SNAPSHOT.jar在window环境下被线程占用，导致mv代码逻辑失败。 

即使我没有配置@EnableFeignClients，也不能卸载

### Actual behavior

A clear and concise description of what actually happened.

### Steps to reproduce

Steps to reproduce the problem:

### Environment

- Koupleless version (see CURRENT_VERSION.txt):
- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Kubernetes version:

**Comment by loong-coder** [comment]
进一步排查发现，只要模块导致了其他依赖，卸载时就会失败，异常信息未变。如图，可以看到插件在卸载时，jar包仍然被java进程占用
![image](https://github.com/koupleless/koupleless/assets/101961800/741d264f-dbdc-44ae-b4cf-79bd0c253c7c)

**Comment by lvjing2** [comment]
fixed by https://github.com/sofastack/sofa-ark/pull/943
