### ISSUE TITLE
koupleless-samples 中springboot-samples 的 forward 问题修复，更新README

### ISSUE THREAD

**Issue by fan2008shuai** [koupleless/koupleless#263]
### Feature description

Describe the feature details with Chinese or English.

### Additional notes

Add other notes if necessary.

**Comment by fan2008shuai** [comment]
@fan2008shuai

**Comment by fan2008shuai** [comment]
已经提交pull request https://github.com/koupleless/samples/pull/34

**Comment by lvjing2** [comment]
回复评论了，麻烦查看下

**Comment by lvjing2** [comment]
已修复 https://github.com/koupleless/samples/pull/40
