### ISSUE TITLE
集成测试框架验证问题

### ISSUE THREAD

**Issue by gaosaroma** [koupleless/koupleless#268]
分支
koupleless-runtime: fix/remove_surefire
koupleless-samples: youji-dev
问题
现象

在 koupleless_samples/springboot-samples/web/tomcat 目录下执行：

mvn test

会报错：
![image](https://github.com/koupleless/koupleless/assets/44571204/e0be5d38-0a47-4dc3-9a44-0ef70c7f0538)

调试方式

mvn -Dmaven.surefire.debug test

然后把 idea 的 remote JVM 端口配置成 5005

排查链路

在模块执行前，查找该模块的启动类（com.alipay.sofa.web.biz1.Biz1Application）时：
● com.alipay.sofa.koupleless.test.suite.spring.biz.BizSpringTestApplication#run
Class<?> mainClass = testBiz.getBizClassLoader()
.loadClass(config.getMainClassName());
  ○ com.alipay.sofa.koupleless.test.suite.biz.TestBizClassLoader#resolveLocalClass
![image](https://github.com/koupleless/koupleless/assets/44571204/49090282-bd32-4c7d-bf93-c5c5d739d479)

    ■ 此时会发现 TestBizClassLoader 找不到这个类，即：clz == null

**Comment by lvjing2** [comment]
1. 解决当前集成测试框架的问题，可以从设计角度出发解决
2. 完成每个 samples 的多应用集成测试，当前由于无法启动测试，所以部分测试当前的跳过的，需要重新打开
  - Encache
  - Cross Service calling
  - web tomcat 当前的 assert 逻辑也是跳过的
