### ISSUE TITLE
MultiBizProperties 在 initSystem 时存在并发问题？

### ISSUE THREAD

**Issue by fan2008shuai** [koupleless/koupleless#269]
![image](https://github.com/koupleless/koupleless/assets/4408340/ad4d9cc1-cc69-4b2a-a5af-bc9aabb888d6)
在基座里面，如果存在两个线程，分别执行如下代码：
```java
MultiBizProperties multiBizProperties = MultiBizProperties.initSystem();
multiBizProperties.setProperty("hello", "world");
String world = multiBizProperties.getProperty("hello");
```
```java
MultiBizProperties multiBizProperties = MultiBizProperties.initSystem();
multiBizProperties.setProperty("sofa", "koupless");
```
线程 A 和线程 B 同时执行到了第 530 行，此时线程 A 先执行，成功 new MultiBizProperties并返回，然后执行`multiBizProperties.setProperty("hello", "world");`。然后线程 B 继续执行，会发生线程 A 的setProperty("hello", "world")被线程 B 覆盖？

为initSystem()和initSystem(String bizClassLoaderName)增加 synchronized 关键字？

**Comment by qq290584697** [comment]
MultiBizProperties.initSystem();应该在基座中调用，且只调用一次
