### ISSUE TITLE
spring-boot 下沉之后 AutoConfiguration 的逻辑没有很好的适配

### ISSUE THREAD

**Issue by 98DE9E1F** [koupleless/koupleless#274]
### Describe the question or bug

只下沉 spring-boot 不下沉 mongo 这种二方包情况下，模块启动的时候会触发基座中的 MongoAutoConfiguration ，而基座中的MongoAutoConfiguration 去加载 mongo 的类是用的基座的 classcloader 所以会报找不到mongo 的

### Expected behavior

既然MongoAutoConfiguration被判断可以加载，那是不是不应该报类找不到，因为本身MongoAutoConfiguration 带有 @ConditionalOnClass(MongoClient.class)  行为有点不一致 

### Screenshots

![image](https://github.com/koupleless/koupleless/assets/16440825/e832e9f5-20fe-4cbf-8f83-0bb4eb5aade7)

- Koupleless version (see CURRENT_VERSION.txt):  2.0.0
- SOFAArk version: 3.0.4
- JVM version (e.g. `java -version`): jdk17

**Comment by lvjing2** [comment]
## 问题原因
测试了下，这段逻辑是在初始化  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration$MongoClientSettingsConfiguration 时，走到了 
![image](https://github.com/koupleless/koupleless/assets/3754074/24cc71e9-b545-4f70-9ac8-000d09e18142)

这里 class 也就是 `org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration$MongoClientSettingsConfiguration` 是基座里的类，执行 `getDeclaredMethods` 是最终会执行到在 class 内部的 native 方式 `getDeclaredMethods0`，该方法只会使用当前 class 所属 classLoader 查找 `MongoClientSettings` 这个模块里的内，所以肯定是找不到的

## 问题解决
目前没有可行的通过设置 classLoader 的方式来修改这段逻辑，只有通过将spring autoconfiguration 相关的类放在基座里解决。

**Comment by lvjing2** [comment]
暂无修复方式，先关闭。
