### ISSUE TITLE
adapter 的包管理方式优化

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#292]
### 问题描述

当前对于某个组件的各种版本的 adapter，统一记录在不同的bundle，导致 bundle 的数量会不断增多，不便于未来的维护。

当前设计是，每个 adapter bundle 引入独立版本的依赖，然后发布成 jar 包到 maven 中央仓库，再有基座打包插件打包时将对应 jar 里的 class 文件拷贝到基座工程中。

这种方式的弊端是
1. 每个组件的历史版本都会有对应的 bundle，bundle 数量较多

![image](https://github.com/user-attachments/assets/183221c0-fbd5-4074-94a1-12f0f9fd6f41)

![image](https://github.com/user-attachments/assets/ff63115e-284e-4137-a2da-61cb55dcb6e1)

### 问题解决

考虑每个组件，只创建一个 bundle，每个 bundle 里维护多个版本，同时改 bundle 也不需要指定 jdk 版本，也不用引入外部依赖。在基座构建的时候，直接将 java source 文件拷贝到工程里，然后执行基座的编译。直接用基座的依赖和jdk版本，将adapter 类编译成 class 文件。

该方法虽然能解决上述两个弊端，但也需注意该方法的另一种弊端，adapter 工程无法构建与编译，代码只是作为文本管理的存在。

**Comment by gaosaroma** [comment]
讨论一下其它解决方案：
对于任一依赖，多个文件的多个不同版本范围都需要做适配，但一旦对该文件适配完毕，基本上不会有新改动。在目前的 adapter 包管理中，产生多个 bundle 的原因是任意新增/修改 adapter，其它 adapter 都会发布一遍；或许思路可以改成，只发布新增/修改的 adapter，从而减少 bundle 的发布；

同时，由于 “多个文件的多个不同版本范围都需要做适配”，如果 “只创建一个 bundle，每个 bundle 里维护多个版本”，那么每次对不同文件的修改都需要修改并发布一次该 bundle。

**Comment by lvjing2** [comment]
fixed by https://github.com/koupleless/runtime/pull/211
