### ISSUE TITLE
dubbo samples 无法正常使用 

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#305]
目前测试发现 dubbo 27的 samples，部署模块之后，无法按照预期完成流量的验证

![image](https://github.com/user-attachments/assets/45814b89-896d-4f90-8ecd-b1988d52a73a)

**Comment by thegenius** [comment]
dubbo 32的samples，默认是依赖zookeeper，能否添加nacos的示例

**Comment by lvjing2** [comment]
dubbo 32 sample 的主要作用是介绍 dubbo 32 在 koupleless 多模块模式下的使用，你想要的是 nacos 在多模块下的使用方式吧，这个可以查看 nacos 的专属 sample 的

**Comment by lvjing2** [comment]
排查发现是由于模块启动的时候，没有发布 dubbo serveice，进一步看是因为模块启动扫描没有注册  `BizDubboBootstrapListener`，没有注册的原因是因为这个 listener 是在 adapter 的 /META-INF/spring.factories 里注册的。

基座打包构建时，adapter 的/META-INF/spring.factories 是 copy 到基座 target 的 local classpath 里的，但是在模块启动的时候，模块扫描 spring.factories 的时候，会通过 declaredMode 做一次判断。只有模块里声明过的依赖里的类和资源，才可以加载。

由于模块实际上是没有声明引入基座的，所以基座里的 /META-INF/spring.factories 里会被 declaredMode 拦截过滤掉。从而导致模块里扫描不到 `BizDubboBootstrapListener`，所以模块里的 dubbo service 无法注册。
