### ISSUE TITLE
【feature】Arkctl 增加错误诊断能力

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#308]
## feature 描述
当前 koupleless 在部署时对于可能出现的问题已经沉淀了一些的 [faq](https://koupleless.io/docs/faq/faq/)，但是当前在模块部署的时候的报错还需要意识到从 faq 里查找问题原因才可能知道怎么处理。

当前实际是可以把这些 faq 转成 arkctl 的诊断规则，在 arkctl deploy 的时候得到报错堆栈的时候，匹配具体的诊断规则，如果报错了之后直接根据诊断结果给出问题如何处理恢复。

**Comment by JunJieLiu51520** [comment]
plz  assgin to me
