### ISSUE TITLE
StackOverflowError 在使用installBiz接口时出现

### ISSUE THREAD

**Issue by qianbidaos** [koupleless/koupleless#334]
在调用接口`http://10.147.19.13:1238/installBiz`时，传入以下参数：

```json
{
    "bizName": "djicamera",
    "bizVersion": "1.0.1",
    "bizUrl": "https://starfly-cloud.obs.cn-south-1.myhuaweicloud.com/jar/djicamera-1.0-SNAPSHOT-ark-biz.jar",
    "args": ["--spring.profiles.active=previewk8s"]
}
```

应用能够加载模块并正常使用，但出现了`StackOverflowError`，错误与`fastjson`库有关。当前`fastjson`版本为`2.0.3`。

**错误日志**:
```
java.lang.StackOverflowError: null
    at com.alibaba.fastjson2.writer.FieldWriter.getObjectWriter(FieldWriter.java:417)
    at com.alibaba.fastjson2.writer.FieldWriterObject.getObjectWriter(FieldWriterObject.java:47)
    at com.alibaba.fastjson2.writer.ObjectWriter_17.write(Unknown Source)
    ...
```

**环境**:
- JDK版本: 17
- Spring Boot版本: 2.7.2
- fastjson版本: 2.0.3

**期望行为**:
接口调用时不应出现`StackOverflowError`。

**尝试的解决方案**:
1. 检查了对象的循环引用。
2. 同步一下`fastjson`更高版本（如`2.0.5`或更高）。
3. 通过`SerializerFeature.DisableCircularReferenceDetect`禁用循环引用检测。JSON.toJSONString(yourObject, SerializerFeature.DisableCircularReferenceDetect);

**Comment by lvjing2** [comment]
你当前尝试的解决方案，是否已经先解决你的问题了呢？

**Comment by qianbidaos** [comment]
使用尝试解决方案2
当前版本2.0.3版本错误必现,2.0.5的版本可用

**Comment by qianbidaos** [comment]
可能原因: fastjson版本2.0.3在特定序列化/反序列化场景中可能存在StackOverflowError的问题。
