### ISSUE TITLE
运营平台能力集成调研

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#44]
基于开源大学堂，https://test.oscollege.net/

1. 对外的视频和上手环境和demo
2. 运营的任务与文章
3. 题库的问答，答疑的沉淀
4. 用户的支持跟进

**Comment by lylingzhen** [comment]
[x] 完成视频课程介绍、旁白文案更新优化。
[ ] 创建实验室环境和容器，配置相关依赖，测试 VSCode WebIDE，跑通 Sample 工程。- 进行中。

**Comment by lylingzhen** [comment]
实验室环境和文档预计 4 月份交付。

**Comment by lvjing2** [comment]
工程复现环境的搭建

**Comment by lylingzhen** [comment]
这个 Issue 先 Close？开源大学堂云版 IDEA 环境已经跑通。
