### ISSUE TITLE
markdown lint, and dead link check

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#62]
markdown ci check for lint and dead link

markdown 的语法检查，无法访问的链接检查

which we can reference from :
1. https://github.com/mosn/layotto/blob/main/.github/dead_link_check_config.json
2. https://github.com/mosn/layotto/blob/main/.github/markdown_lint_config.json

**Comment by lylingzhen** [comment]
4 月份交付。

**Comment by lylingzhen** [comment]
Done. Close the issue.
