### ISSUE TITLE
support sprinngboot 3.2

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#72]
There is some test failed in runtime, which means we need to do something support springboot 3.2

![image](https://github.com/koupleless/koupleless/assets/3754074/de86d08b-1ab1-42f4-96c1-25d300aeabff)

but all those test is success in jdk8
![image](https://github.com/koupleless/koupleless/assets/3754074/b62c3367-e098-418a-ae19-9edaa1d0f344)

**Comment by gaosaroma** [comment]
使用 koupleless 2.1.0 没有遇到该问题：
![image](https://github.com/koupleless/koupleless/assets/44571204/699e7cd3-b355-4b69-befc-b0a7b6663c20)
