### ISSUE TITLE
SpringServiceFinder.listModuleServices 在启动时会报错 `biz state is not valid`

### ISSUE THREAD

**Issue by lvjing2** [koupleless/koupleless#77]
## 问题描述
在中台模式下，基座调用模块服务。

模块在启动过程中，触发基座更新模块的服务列表，这时候会调用 `SpringServiceFinder.listModuleServices`，然而这时候模块还没完全启动结束，模块状态还是 resolved，在这行 listModuleSerices 时会检查模块状态，然后报这段错误：

![image](https://github.com/koupleless/koupleless/assets/3754074/d4f1aab9-0703-459e-a821-8df9eb8d3edf)

## 问题解决方案
考虑放宽该处状态检查逻辑

**Comment by linwaiwai** [comment]
suggesion: Adding some state to indicate the Biz api could be called

**Comment by lvjing2** [comment]
biz state=ACTIVATED support to be called, already fixed
