### ISSUE TITLE
The master biz netty server was close when uninstalling the biz

### ISSUE THREAD

**Issue by linwaiwai** [koupleless/koupleless#85]
### Describe the question or bug

First, setting the spring application Context .
```
SpringApplication springApplication = new SpringApplication(FizzBootstrapApplication.class);
springApplication.setApplicationContextClass(CustomReactiveWebServerApplicationContext.class);
```
     
install the biz with code or telnet:
```
biz -a ${packageName}
biz -u ${packageName}
```
Acording my observing , The biz start with the master context , which is wrong.

When the biz is uninstalling, the application Conxtext will be closed leading netty server to close the port 

### Expected behavior

The biz should be use its application Context created by itself.

### Actual behavior

The biz uses the master biz

### Environment

- Koupleless version (see CURRENT_VERSION.txt):0.5.6
- SOFAArk version:3.1.3 (v3.1.3)
- JVM version (e.g. java -version): 18
- OS version (e.g. uname -a): Darwin MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct 9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 x86_64
- Kubernetes version: none

**Comment by linwaiwai** [comment]
the pom should quote：
 <dependency>
      <groupId>com.alipay.sofa</groupId>
      <artifactId>netty-ark-plugin</artifactId>
      <version>2.2.7</version>
  </dependency>

I do add it .
But the 2.2.7 code still exists probleme , for it always boot its netty server with port:8080 . It should be fixed

**Comment by lvjing2** [comment]
![image](https://github.com/koupleless/koupleless/assets/3754074/5b69aa04-390a-49fc-89d0-aff6a776cce1)
看了下你的代码，这里需要做下适配，改成 classLoader 为 key 的map类型了。框架部分无法帮助完成，需要实现的这部分带来做调整
